[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "the-git-saver"
version = "0.1.3"

[tool.semantic_release]
branch = "main"
tag_format = "v{version}"
commit_parser = "conventional"
allow_zero_version = true
changelog_file = "CHANGELOG.md"

version_toml = [
    "pyproject.toml:project.version"
]

[tool.semantic_release.remote]
name = "origin"