[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "the-git-saver"
version = "0.3.3"

[tool.semantic_release]
branch = "main"

tag_format = "ver{version}"

commit_parser = "conventional"

allow_zero_version = true

changelog_file = "CHANGELOG.md"

version_toml = [
    "pyproject.toml:project.version"
]

commit_message = "chore(release): {version} [skip ci]"

build_command = ""

upload_to_pypi = false

[tool.semantic_release.remote]
name = "origin"

[tool.semantic_release.publish]
dist_glob_patterns = [
    "dist/*.exe"
]