name: Build EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - run: pip install -r requirements.txt
      - run: pip install pyinstaller

      - run: .\build.bat

      - uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/